### ISSUE TITLE
Cardano-wallet alternate wallet repo ak3n/cw is not accessible

### ISSUE THREAD

**Issue by tomazvila** [james-iohk/plutus-scripts#1]
# Expected behaviour

Project compiles fine

# Issue
```
cabal build
Cloning into '/home/tomazvila/project/dist-newstyle/src/cw-5066f6a8904d74b'...
remote: Repository not found.
fatal: repository 'https://github.com/ak3n/cw/' not found
```

To me it seems that `ak3n/cw` is not accessible and is not public repository so it is not possible to build this project without access to that repository

**Comment by catch-21** [comment]
Thanks. Now resolved.
